### ISSUE TITLE
Some trailers are not downloaded

### ISSUE THREAD

**Issue by forthrin** [aag/apple_trailer_downloader#20]
Currently, the trailers "Downhill" and "A Quiet Place Part II" are under "Just Added" on the Apple website, but do not download with the script.

An additional issue may be that the latter one only has a "Trailer 2" (no "Trailer 1"), which is an edge case that raises questions on whether the "single trailer" option should download whichever trailer is the first one published regardless of its type. (I realise that this is not a trivial fix and will cause backwards compatibility problems).

However "Downhill" has a "Trailer", so it's unclear why it's not downloaded. This could possibly mean there are other trailers not downloaded too, which would be bad. The user must be able to trust the script to get everything.

**Comment by aag** [comment]
I've updated the script to handle both of these cases.

In the case of "Downhill", the trailer title was "Trailer " (notice the space after the word).

I've also changed the behavior in cases where there is no "Trailer" or "Trailer 1", but there is some other trailer. The script will now download the other trailer. If a "Trailer" or "Trailer 1" appears on the site later, the script will not download it, because it's already downloaded a single trailer for that movie.

Please update to latest master or download v1.0.0-beta3 to get the fix.

**Comment by forthrin** [comment]
I regret to say that this fix has introduced a bug where a couple of dozen trailers (eg. the Top Gun trailers) are downloaded again and again each time the script is run. Also, they are added multiple times to the `.lst` file. Would reopen the issue, but the button is missing.

**Comment by aag** [comment]
Thanks for reporting the new bug. I've just released a new version that fixes this problem. Please update to latest master or download v1.0.0-beta4 and let me know if you find any other problems.
