### ISSUE TITLE
Suggest to merge with youtube-dl

### ISSUE THREAD

**Issue by forthrin** [aag/apple_trailer_downloader#9]
`youtube-dl` almost supports all the functionality in Apple Trailers Downloader. Would you be willing to merge the missing functionality into `youtube-dl`? See https://github.com/rg3/youtube-dl/issues/7924

This would make ATD superfluous really, and `youtube-dl` has become so powerful that it makes sense to put energy into that instead. It's written in Python also.

**Comment by aag** [comment]
It's not really possible to copy the ATD code into youtube-dl, especially since they don't want to depend on BeautifulSoup, a library used throughout the ATD code. Someone would have to reimplement the ATD functionality in a way that makes sense within the youtube-dl architecture and refactor the code that uses BeautifulSoup.

I'm not especially interested in doing that work, but anyone else is welcome to use ATD as a reference if they want to add the functionality to youtube-dl.

**Comment by forthrin** [comment]
https://github.com/rg3/youtube-dl/issues/7924#issuecomment-166849585
